version: '3.8'

services:
  python-app:
    image: linckon/python-app:v1
    container_name: python-app
    ports:
      - "5000:5000"
    environment:
      - MY_ENV_VAR=Running_From_python-app_Container

  spring-boot-app:
    image: linckon/spring-boot-app:v1
    container_name: spring-boot-app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=Running_From_spring-boot-app_Container
    depends_on:
      - python-app